# Generated by Django 5.1.1 on 2024-09-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contactsubmission_remove_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
